CREATE TABLE USUARIO (
   id SERIAL PRIMARY KEY,
   nome VARCHAR(255) NOT NULL,
   ativo BOOLEAN DEFAULT TRUE,
   senha VARCHAR(255) NOT NULL,
   criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS RECEITA (
    ID SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	ingredients TEXT NOT NULL,
	instrucoes TEXT NOT NULL,
	tempo_preparo_minutos INTEGER NOT NULL,
	usuario_id INTEGER NOT NULL REFERENCES USUARIO(id) ON DELETE CASCADE
	
  );


  